apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: g1r1qrhzi-python 
  janus-idp.io/tekton: g1r1qrhzi-python
  backstage.io/kubernetes-id: g1r1qrhzi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g1r1qrhzi-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml